# About
title: Strategic Writing
description: SVA MFA IXD Spring 2017
url: http://strategicwriting.club
author:
    name: Nicole Fenton
    email: nfenton1@sva.edu
    url: https://nicolefenton.com
github:
  repo:              https://github.com/nicoleslaw/strategicwriting

# Dependencies
markdown: kramdown

baseurl:  "/"

# Permalinks
permalink: pretty

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock

paginate:         5
