# About

title: Strategic Writing
tagline: SVA MFA IXD Spring 2017
description: 
url: "http://strategicwriting.club"
author: 
    name: Nicole Fenton
    email: nfenton1@sva.edu
    url: https://nicolefenton.com


# Settings

paginate: 1
baseurl: ""
permalink: pretty

sass:
  sass_dir:          _sass
  style:            :compressed

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
